### ISSUE TITLE
Arrumar o erro de variáveis da versão em pt-BR do readme.md

### ISSUE THREAD

**Issue by Mocje** [matheuscas/pycpfcnpj#23]
As variáveis ```masked_cpf_number```, ```cpf_number_mascara```, ```masked_cnpj_number``` e ```cnpj_number_mascara``` na documentação do arquivo _"readme.MD"_ não se relacionam.

**Comment by matheuscas** [comment]
Oi @Mocje . Você tem razão. Não quer enviar um PR não? :)

**Comment by Mocje** [comment]
vou tentar lol (_minha primeira vez usando isso no github_)

**Comment by Mocje** [comment]
Issue #23 fechado, por que já existe um pr (#24) aberto
