### ISSUE TITLE
Deprecation warning due to invalid escape sequences 

### ISSUE THREAD

**Issue by tirkarthi** [matheuscas/pycpfcnpj#26]
Deprecation warning due to invalid escape sequences. Using raw strings or escaping them again helps in resolving this.

```
find . -iname '*py' | grep -Ev 'setup|rdf4|tool' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./pycpfcnpj/compatible.py:6: DeprecationWarning: invalid escape sequence \D
  return re.sub('\D', '', str(document))
```

**Comment by jsousaguiar** [comment]
Could the fix be just to insert 'r' to set raw strings in return re.sub(r'\D', '', str(document))?
