### ISSUE TITLE
Adicionar uma validação extra no clear punctuation

### ISSUE THREAD

**Issue by jeffersonkr** [matheuscas/pycpfcnpj#39]
Casos aonde funciona pois temos as condicionais
![image](https://user-images.githubusercontent.com/36552733/166075236-c0e4cb88-36ee-4e43-8c5a-26a0d8ccb4e4.png)

```
>>> from pycpfcnpj import cpfcnpj
>>> cpfcnpj.validate('+123')
False
```

Casos que quebra o código pois ele da match em umas da condicionais
```
>>> cpfcnpj.validate("+5575999769162")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jkwak/.local/lib/python3.8/site-packages/pycpfcnpj/cpfcnpj.py", line 24, in validate
    return cnpj.validate(clean_number)
  File "/home/jkwak/.local/lib/python3.8/site-packages/pycpfcnpj/cnpj.py", line 28, in validate
    if (first_digit == calc.calculate_first_digit(first_part) and
  File "/home/jkwak/.local/lib/python3.8/site-packages/pycpfcnpj/calculation.py", line 28, in calculate_first_digit
    sum = sum + int(number[i]) * weights[i]
ValueError: invalid literal for int() with base 10: '+'
```

Precisamos validar antes de ir para o validate se existes esses caracteres especiais e retornar Falso caso exista.

**Comment by matheuscas** [comment]
Eu tenho dúvidas sobre isso. `cpfcnpj` assume que você está passando um numero de CPF/CNPJ seja ele valido ou não. Nesse caso vc está passando qualquer coisa, como um número de telefone. Isso abre espaço para validar qualquer outra coisa.

**Comment by jeffersonkr** [comment]
Como exemplo coloquei um telefone, mas era apenas para demonstrar que o `"+"` faz com que a lib quebre, como qualquer outro simbolo que não seja `".", "/","-"`.

A intenção dessa issue é manter o retorno anterior igual ao oque era antes da correção do clear_punctuation, antes mesmo enviando caracteres especiais sendo um documento invalido retornava False pois era um regex que pegava digitos apenas, agora o clear_punctuation apenas altera os valores de `".", "/","-"` para `""`.

Hoje devido a melhoria implantada quando enviado qualquer caracteres especiais que não são os de cima ele quebra dando raise em ValueError.

Entendo que deveriamos mandar apenas digitos e pontos relevantes para a validação do documento, porem na pratica não conseguimos controlar os usuários, são imprevisiveis hehe, então acredito devemos lidar com esses caracteres especiais para que a lib não quebre e manter o retorno original da lib.
