### ISSUE TITLE
Como aplicar o validador em um df?

### ISSUE THREAD

**Issue by victormiya1** [matheuscas/pycpfcnpj#45]
Olá, parabéns pelo trabalho.
Estou tentando aplicar seu validador em uma lista de CNPJs e CPFs e um DF (vieram de um XLSX).
No entanto quando tento o código abaixo apresenta o erro: AttributeError: 'Series' object has no attribute 'translate'

`df['Valida'] = cpfcnpj.validate(df['CNPJ'])`

conseguiria me ajudar?

**Comment by jeffersonkr** [comment]
o validate espera que venha um string como parametro e não um tipo Series
