### ISSUE TITLE
Return false when there is just one digit

### ISSUE THREAD

**Issue by rodfersou** [matheuscas/pycpfcnpj#7]
In [4]: cpfcnpj.validate('11111111111')
Out[4]: True

In [5]: cpfcnpj.validate('22222222222')
Out[5]: True

**Comment by matheuscas** [comment]
It was already implemented.

**Comment by rodfersou** [comment]
@matheuscas yeap, I did in a previous pull request https://github.com/matheuscas/pycpfcnpj/pull/9 I think we forget to close the issue :)
